name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
                cache: 'npm'
                cache-dependency-path: 'app/package-lock.json'

            - name: Install Dependencies
              working-directory: app
              run: npm ci

            - name: Lint & Unit Test (if present)
              working-directory: app
              run: |
                npm run lint --if-present
                npm test --if-present

            - name: Build (if CAP or build script present)
              working-directory: app
              run: npm run build --if-present

            - name: Package Artifact
              run: |
               zip -r artifact.zip app manifest.yml || true

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: cap-sample-artifact
                path: artifact.zip
